### ISSUE TITLE
將日期格式從 {"year":2023,"month":2,"day":9} 改成 2023年2月9日

### ISSUE THREAD

**Issue by ronnywang** [openfunltd/twcompany#26]

**Comment by typingmonk** [comment]
資料庫中日期相關的都用 `{"year":yyyy,"month":mm,"day":dd} ` 的格式儲存。
打算在 [webdata/views/index/data_show.phtml](https://github.com/openfunltd/twcompany/blob/master/webdata/views/index/data_show.phtml) 中把日期都改成 `yyyy年xx月xx日`

pseudo code example:
```php
} elseif ('{"year":' == substr($this->value, 0, 8)) {
<?= format_date($this->value) ?>
}
```

**Comment by typingmonk** [comment]
已完成，請 @ronnywang review code

**Comment by ronnywang** [comment]
沒問題喔，感謝，請推上線吧

**Comment by typingmonk** [comment]
已推上正式環境

**Comment by ronnywang** [comment]
好的，感謝！
